### ISSUE TITLE
Compatibility to "older" pages

### ISSUE THREAD

**Issue by Pasley70** [ColdTrick/pages_tools#12]
If you want to use pages tools  at a later date (hierarchical Pages are already created) pages seem to be incompatible: pages_tools_is_valid_page() returns false and the sidebar module will not be displayed.

Is there a way to make the previous pages compatible with pages_tools?

**Comment by jdalsem** [comment]
previous pages should be compatible. A sidebar tree is only show for 1 tree (1 top page and all its children) and only if it has children (so if there are no subpages, there is no tree). The function `pages_tools_is_valid_page()` only checks the subtype of the entities, so i do not think this function has anything to do with your issue. Can you confirm that the page you are looking at has children (or a parent)??

**Comment by jdalsem** [comment]
I tried to reproduce this, but i am not possible. Please let me know if you have ways to produce your problem.
