### ISSUE TITLE
Fatal error in 1.12.8

### ISSUE THREAD

**Issue by gerard-kanters** [ColdTrick/pages_tools#17]
This line https://github.com/ColdTrick/pages_tools/blob/master/lib/functions.php#L390 produces a 500 error in Elgg 1.12 because that class does not exist.

I changed it to 

$locator = new  \Elgg\EntityDirLocator($entity->getGUID());

which works fine. I am not sure when this class has been changed. This is just a heads for you. 

I also came across this with event manager. Same issue, same solution

**Comment by jdalsem** [comment]
It has been changed in Elgg 1.10 in core. This plugins still needs to be updated... The latest versions of Event Manager do not have this problem.
