### ISSUE TITLE
No menu entry

### ISSUE THREAD

**Issue by dploeger** [ColdTrick/pages_tools#20]
Hm... maybe I'm blind, but I installed the plugin, activated it, installed DomPDF and also reset the caches, but I don't see any menu item for exporting a page. I'm on Elgg 3.2.1.

**Comment by jdalsem** [comment]
did you enable it in the plugin settings?

**Comment by dploeger** [comment]
Yes I did.

**Comment by jdalsem** [comment]
the icon should appear in the 'entity' menu... where you also can find the edit/delete menu items

**Comment by dploeger** [comment]
I thought so. However, only "Subscribe", "History", "Edit" and "Delete" are visible:

![image](https://user-images.githubusercontent.com/203453/69939637-ab74a680-14e0-11ea-93b5-387a58d9e80d.png)

**Comment by dploeger** [comment]
And this is my settings:

![image](https://user-images.githubusercontent.com/203453/69939666-be877680-14e0-11ea-9258-b755f376544b.png)

**Comment by dploeger** [comment]
Also, the plugin is the last in the list, so other plugins shouldn't override its stuff.

**Comment by jdalsem** [comment]
will check it out

**Comment by dploeger** [comment]
Awesome. Tell me, if you need more detail.

**Comment by jdalsem** [comment]
Thanks for reporting. There was a bug in the hook registration

**Comment by dploeger** [comment]
Awesome. Any idea when you can get this into an official release?

**Comment by jdalsem** [comment]
probably around 10/11 december
