### ISSUE TITLE
pages widget in groups context

### ISSUE THREAD

**Issue by jdalsem** [ColdTrick/pages_tools#8]
Widget Manager registers the default widget for the group context, however the "more pages" url in this widget, does not support groups. Maybe this plugin should take over the content view to enhance it for groups.

**Comment by jeabakker** [comment]
related commit 062af893fd6e8bff2dfdcdc51fcc8c7c59d5a5b6

**Comment by jdalsem** [comment]
closed in https://github.com/ColdTrick/pages_tools/commit/062af893fd6e8bff2dfdcdc51fcc8c7c59d5a5b6
